using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KeyBoardSwitcherByConsole
{
    class DefineBox
    {
        List<Define> KeySwitch =new List<Define>
        {
            new Define("a","KEY_A"),
            new Define("b","KEY_B"),
            new Define("c","KEY_C"),
            new Define("d","KEY_D"),
            new Define("e","KEY_E"),
            new Define("f","KEY_F"),
            new Define("g","KEY_G"),
            new Define("h","KEY_H"),
            new Define("i","KEY_I"),
            new Define("j","KEY_J"),
            new Define("k","KEY_K"),
            new Define("l","KEY_L"),
            new Define("m","KEY_M"),
            new Define("n","KEY_N"),
            new Define("o","KEY_O"),
            new Define("p","KEY_P"),
            new Define("q","KEY_Q"),
            new Define("r","KEY_R"),
            new Define("s","KEY_S"),
            new Define("t","KEY_T"),
            new Define("u","KEY_U"),
            new Define("v","KEY_V"),
            new Define("w","KEY_W"),
            new Define("x","KEY_X"),
            new Define("Y","KEY_Y"),
            new Define("z","KEY_Z"),
            new Define("1","KEY_1"),
            new Define("2","KEY_2"),
            new Define("3","KEY_3"),
            new Define("4","KEY_4"),
            new Define("5","KEY_5"),
            new Define("6","KEY_6"),
            new Define("7","KEY_7"),
            new Define("8","KEY_8"),
            new Define("9","KEY_9"),
            new Define("0","KEY_0"),
            new Define("/F1/","KEY_F1"),
            new Define("/F2/","KEY_F2"),
            new Define("/F3/","KEY_F3"),
            new Define("/F4/","KEY_F4"),
            new Define("/F5/","KEY_F5"),
            new Define("/F6/","KEY_F6"),
            new Define("/F7/","KEY_F7"),
            new Define("/F8/","KEY_F8"),
            new Define("/F9/","KEY_F9"),
            new Define("/F10/","KEY_F10"),
            new Define("/F11/","KEY_F11"),
            new Define("/F12/","KEY_F12"),
            new Define("/Enter/","KEY_ENTER"),
            new Define("/Space/","KEY_SPACE"),
            new Define("+LCtrl","MOD_CONTROL_LEFT"),
            new Define("+RCtrl","MOD_CONTROL_RIGHT"),
            new Define("+LShift","MOD_SHIFT_LEFT"),
            new Define("+RShift","MOD_SHIFT_RIGHT"),
            new Define("+LAlt","MOD_ALT_LEFT"),
            new Define("+RAlt","MOD_ALT_RIGHT"),
            new Define("+LGui","MOD_GUI_LEFT"),
            new Define("+RGui","MOD_GUI_RIGHT"),
            new Define("A","KEY_A,MOD_SHIFT_LEFT"),
            new Define("B","KEY_B,MOD_SHIFT_LEFT"),
            new Define("C","KEY_C,MOD_SHIFT_LEFT"),
            new Define("D","KEY_D,MOD_SHIFT_LEFT"),
            new Define("E","KEY_E,MOD_SHIFT_LEFT"),
            new Define("F","KEY_F,MOD_SHIFT_LEFT"),
            new Define("G","KEY_G,MOD_SHIFT_LEFT"),
            new Define("H","KEY_H,MOD_SHIFT_LEFT"),
            new Define("I","KEY_I,MOD_SHIFT_LEFT"),
            new Define("J","KEY_J,MOD_SHIFT_LEFT"),
            new Define("K","KEY_K,MOD_SHIFT_LEFT"),
            new Define("L","KEY_L,MOD_SHIFT_LEFT"),
            new Define("M","KEY_M,MOD_SHIFT_LEFT"),
            new Define("N","KEY_N,MOD_SHIFT_LEFT"),
            new Define("O","KEY_O,MOD_SHIFT_LEFT"),
            new Define("P","KEY_P,MOD_SHIFT_LEFT"),
            new Define("Q","KEY_Q,MOD_SHIFT_LEFT"),
            new Define("R","KEY_R,MOD_SHIFT_LEFT"),
            new Define("S","KEY_S,MOD_SHIFT_LEFT"),
            new Define("T","KEY_T,MOD_SHIFT_LEFT"),
            new Define("U","KEY_U,MOD_SHIFT_LEFT"),
            new Define("V","KEY_V,MOD_SHIFT_LEFT"),
            new Define("W","KEY_W,MOD_SHIFT_LEFT"),
            new Define("X","KEY_X,MOD_SHIFT_LEFT"),
            new Define("Y","KEY_Y,MOD_SHIFT_LEFT"),
            new Define("Z","KEY_Z,MOD_SHIFT_LEFT"),
            new Define("!","KEY_1,MOD_SHIFT_LEFT"),
            new Define("@","KEY_2,MOD_SHIFT_LEFT"),
            new Define("#","KEY_3,MOD_SHIFT_LEFT"),
            new Define("$","KEY_4,MOD_SHIFT_LEFT"),
            new Define("%","KEY_5,MOD_SHIFT_LEFT"),
            new Define("^","KEY_6,MOD_SHIFT_LEFT"),
            new Define("&","KEY_7,MOD_SHIFT_LEFT"),
            new Define("*","KEY_8,MOD_SHIFT_LEFT"),
            new Define("(","KEY_9,MOD_SHIFT_LEFT"),
            new Define(")","KEY_0,MOD_SHIFT_LEFT"),
            new Define("/Esc/","KEY_ESCAPE","0x29"),
            new Define("/Backspace/","KEY_BACKSPACE","0x2A"),
            new Define("/Tab/","KEY_TAB","0x2B"),
            new Define("-","KEY_-","0x2D"),
            new Define("=","KEY_=","0x2E"),
            new Define("+","KEY_+","0x2E"),



        };

    }
}
